### ISSUE TITLE
Flx matching drops duplicates

### ISSUE THREAD

**Issue by ancane** [kostafey/popup-switcher#11]
Hi. There is small problem for `popup-imenu` in regard to flex matching: it doesn't tolerate duplicates at the moment. The thing is that imenu may contain items, like overloaded methods, that I'd like to match and switch between them. My suggestion would be to drop `flx-ido` dependency and implement `flx-popup` here, to be able to fully control `flx` match in a way, appropriate for particular switching function. What do you think?

**Comment by kostafey** [comment]
Hi! Well, from the point of view of the emacs community, it's better to have interoperated modules best at their own data domain. `flx` package is good enough at fuzzy matching and suitable to use in many other packages, not only ours. First we have to try bring such possibility to `flx` `flx-ido-match-internal` as optional. Did you ask it's author about it?

**Comment by ancane** [comment]
Thanks, I'll check with `flx` repo first.

**Comment by kostafey** [comment]
What is the actual state of issue? I've removed eassist, so popup-switcher uses imenu for functions navigation only.
