### ISSUE TITLE
feature request - option to not close the popup if you close a buffer you are currently viewing

### ISSUE THREAD

**Issue by jla1** [kostafey/popup-switcher#12]
I installed popup-switcher to quickly close buffers without having to open ibuffer, and it would speed things up by not having to open it multiple times. 

edit: nvm, I checked the closed issue and see it's not possible.

**Comment by kostafey** [comment]
It seems, I was wrong here https://github.com/kostafey/popup-switcher/issues/7 :).
It's possible. Fixed.
