### ISSUE TITLE
psw-navigate-files current directory

### ISSUE THREAD

**Issue by Compro-Prasad** [kostafey/popup-switcher#13]
Add the `.` directory to the list so that we can utilize the `dired-mode` too.

**Comment by kostafey** [comment]
What kind of action do you expect from choosing `.` in a list?

**Comment by Compro-Prasad** [comment]
The current directory should open in `dired-mode`

**Comment by kostafey** [comment]
@Compro-Prasad, since this behavior is not by default, please add the following to your `.emacs`:
```
(setq psw-enable-single-dot-to-navigate-files t)
```

**Comment by Compro-Prasad** [comment]
Thanks!
