### ISSUE TITLE
Highlight current buffer

### ISSUE THREAD

**Issue by yanglimingcn** [kostafey/popup-switcher#16]
psw-switch-buffer list buffer menu, always highlight current file, I think highlight previous buffer will be better.

**Comment by kostafey** [comment]
@yanglimingcn, looks fixed. Could you please try the latest update and add this setting to you `.emacs`:
https://github.com/kostafey/popup-switcher#highlight-previous-buffer-for-psw-switch-buffer

**Comment by yanglimingcn** [comment]
looks good, good job, thanks.
