### ISSUE TITLE
Readme screenshots "not found"

### ISSUE THREAD

**Issue by duianto** [kostafey/popup-switcher#17]
The readme screenshots show a broken image icon, at the bottom of the `Usage` section:
https://github.com/kostafey/popup-switcher#usage

Clicking on them opens a blank page with the text: `Not Found`

They link to:
```
<img src="https://dl.dropboxusercontent.com/u/820526/psw-switch-buffer.png" width="600" />
<img src="https://dl.dropboxusercontent.com/u/820526/psw-switch-function.png" width="600" />
```
It might be better to host them on Github.

**Comment by kostafey** [comment]
Fixed.
