### ISSUE TITLE
popup-switcher does not work

### ISSUE THREAD

**Issue by pa23** [kostafey/popup-switcher#5]
popup-switcher does not work already long time. It just does not show popup menu. Environment: Arch Linux, GNU Emacs 24.4.1, popup 20141215.349 (0.5.2). popup-switcher 20141224.326 (0.2.6).
Backtrace:
Debugger entered--Lisp error: (void-function remove-if)
  (remove-if (function (lambda (buf) (or (minibufferp buf) (let ((buf-name (buffer-name buf))) (and (>= (length buf-name) 2) (equal (substring buf-name 0 2) " *")))))) (buffer-list))
  psw-get-buffer-list()
  (psw-switcher :items-list (psw-get-buffer-list) :item-name-getter (quote buffer-name) :switcher (quote switch-to-buffer))
  psw-switch-buffer()
  call-interactively(psw-switch-buffer nil nil)
  command-execute(psw-switch-buffer)

**Comment by kostafey** [comment]
It seems I'm too old-fashioned since I still use Emacs 24.3 :).
I believe it fixed in popup-switcher 0.2.7.
Thank you for bug report.

**Comment by pa23** [comment]
I tested popup-switcher 0.2.7.

Backtrace:
Debugger entered--Lisp error: (void-function lexical-let)
  (lexical-let ((lex-funs funs)) (function (lambda (&rest args) (reduce (quote funcall) (butlast lex-funs) :from-end t :initial-value (apply (car (last lex-funs)) args)))))
  psw-compose(psw-get-plain-string buffer-name)
  (funcall (psw-compose (quote psw-get-plain-string) item-name-getter) x)
  (lambda (x) (funcall (psw-compose (quote psw-get-plain-string) item-name-getter) x))(#<buffer popup-switcher.el>)
  mapcar((lambda (x) (funcall (psw-compose (quote psw-get-plain-string) item-name-getter) x)) (#<buffer popup-switcher.el> #<buffer *scratch*> #<buffer *Messages*>))
  (let ((item-names-list (mapcar (function (lambda (x) (funcall (psw-compose ... item-name-getter) x))) items-list))) (funcall switcher (psw-get-item-by-name :item-names-list item-names-list :items-list items-list :target-item-name (psw-popup-menu item-names-list))))
  (progn (run-hooks (quote psw-before-menu-hook)) (let ((item-names-list (mapcar (function (lambda (x) (funcall ... x))) items-list))) (funcall switcher (psw-get-item-by-name :item-names-list item-names-list :items-list items-list :target-item-name (psw-popup-menu item-names-list)))) (run-hooks (quote psw-after-switch-hook)))
  (let* ((items-list (car (cdr (plist-member --cl-rest-- (quote :items-list))))) (item-name-getter (car (cdr (plist-member --cl-rest-- (quote :item-name-getter))))) (switcher (car (cdr (plist-member --cl-rest-- (quote :switcher)))))) (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote (:items-list :item-name-getter :switcher :allow-other-keys))) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:items-list :item-name-getter :switcher)" (car --cl-keys--)))))) (progn (run-hooks (quote psw-before-menu-hook)) (let ((item-names-list (mapcar (function (lambda ... ...)) items-list))) (funcall switcher (psw-get-item-by-name :item-names-list item-names-list :items-list items-list :target-item-name (psw-popup-menu item-names-list)))) (run-hooks (quote psw-after-switch-hook))))
  psw-switcher(:items-list (#<buffer popup-switcher.el> #<buffer *scratch*> #<buffer *Messages*>) :item-name-getter buffer-name :switcher switch-to-buffer)
  psw-switch-buffer()
  call-interactively(psw-switch-buffer nil nil)
  command-execute(psw-switch-buffer)

You should update your Emacs )
